### ISSUE TITLE
install-ziglint should clean up ziglint_src directly if it had to build from source

### ISSUE THREAD

**Issue by scheibo** [AnnikaCodes/install-ziglint#3]
![Screenshot 2023-07-22 at 18 23 45](https://github.com/AnnikaCodes/install-ziglint/assets/117249/984cb357-dd8b-417e-be2c-a042be32058d)

alternatively move ziglint_src to a higher level so that the files dont get put in the same tree as the main checkout

**Comment by AnnikaCodes** [comment]
This should be fixed as of 59562249cb80eeaf113bda80a8323526deb21364.
